civersion: "2"
services:
  mysql:
    environment:
      MYSQL_DATABASE: vufind
      MYSQL_USER: vufind 
      MYSQL_PASSWORD: vufind
      MYSQL_ROOT_PASSWORD: root
    image: mysql
    ports:
      - 3306:3306      
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ${PWD}/mongosocket:/tmp
  vu-find:
    image: ubuntu:xenial
    ports:
      - 8080:80
      - 8081:8080
    links:
      - mysql
      - mongodb
    volumes:
      - ${PWD}/mongosocket:/tmp/mongosocket
#    command: /bin/bash
    command: bash -c "/usr/local/vu-find/solr.sh start; /usr/sbin/apache2ctl -D FOREGROUND"
    tty: true
    stdin_open: true
registries: {}
