version: "2"
services:
  mongodb:
    image: mongo
    volumes:
      - ${PWD}/mongosocket:/tmp
  vu-find:
    image: ubuntu:xenial
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/mongosocket:/tmp/mongosocket
    command: /bin/bash
    tty: true
    stdin_open: true

registries: {}
